name: Docker Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          cd webApp
          DOCKER_BUILDKIT=1 docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app-server:latest .

      - name: Push Docker image to Docker Hub
        run: |
          cd webApp
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app-server:latest

      # Step to authenticate using the service account key
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step to set up Google Cloud CLI
      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Optional: Verify authentication
      - name: Test Google Cloud CLI Authentication (optional)
        run: |
          gcloud auth list
          gcloud config list

      # Deploy Docker image to Google Cloud Run
      - name: Deploy Docker Image to Google Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image docker.io/${{ secrets.DOCKER_USERNAME }}/flask-app-server:latest \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated \
            --memory 1Gi \
            --timeout=300s
