name: Docker Build and Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch (or any branch you prefer)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker image
        run: |
          cd webApp
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app-demo:latest .

      - name: Push Docker image to Docker Hub
        run: |
          cd webApp
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app-demo:latest

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS Access Key
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS Secret Key
          aws-region: ap-south-1 # AWS Region, adjust as necessary

      - name: Install Elastic Beanstalk CLI
        run: |
          curl -sL https://github.com/aws/aws-elastic-beanstalk-cli-setup/raw/master/scripts/install_dependencies | sudo bash
          sudo apt-get install -y python3-pip
          pip3 install awsebcli --upgrade --user
          
      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p docker flask-app-demo --region ap-south-1
          eb use flask-app-demo-env # Elastic Beanstalk environment name
          eb deploy
